### ISSUE TITLE
Unable to get property 'serverUrl' of undefined or null reference

### ISSUE THREAD

**Issue by amitkarn** [betajs/react-betajs-media-component#6]
While recording using betajs using BetaJSVideoRecorder on edge 42.17134.1.0, this error message pops up in console 

> Unable to get property 'serverUrl' of undefined or null reference. @sambua

**Comment by sambua** [comment]
Hello @amitkarn this is because Edge is not fully supports WebRTC MediaRecorder, you need to use another media server like `Wowza` media server.
