### ISSUE TITLE
Im unable to pause while recording the video

### ISSUE THREAD

**Issue by BashaAlam** [betajs/react-betajs-media-component#7]
I have tried to pause the video using this.betaRef.recorder.pause(), but it does not pause the video

**Comment by sambua** [comment]
Hello @BashaAlam 


Sorry but currently pause recorder feature is not ready. You can stop the Recorder or pause the Player but not pause recorder.

It's in our todo list to add this feature. If anyone want to contribute we could be only happy :)

Thanks

**Comment by BashaAlam** [comment]
Do I have any other way to pause the video?

**Comment by sambua** [comment]
Pause video during recording? No sorry for now it's not possible. But pause player sure.

**Comment by BashaAlam** [comment]
When can I expect pause functionality?

**Comment by sambua** [comment]
Hello @BashaAlam ,

During this week will update with all new features not only pause/resume recorder. But initially it will be for webRTC recorder only.
